### ISSUE TITLE
Algorithm 8 pseudocode: ê(θ,t) update

### ISSUE THREAD

**Issue by thorinf** [Algomancer/Bayesian-Flow-Networks#5]
Hi,

Any idea what this line in the pseudocode is meant to be? I've not been able to get my head around what e<sub>k</sub> is. 

Not had an email back from authors, unfortunately.

![image](https://github.com/Algomancer/Bayesian-Flow-Networks/assets/91201457/37aed342-56f9-41ce-a4dc-aefab66aaf55)

In the sampler e<sub>k</sub> is the one hot encoding sampled from the distribution. This would mean that ê(θ,t) is the summation through k for all probabilities given we chose k? But with the probabilities summing to 1, the summation should also sum to 1?

It's quite confusing.

I see in your implementation that you just use the softmax to take the L2 between the one-hot encoding, which is nice and makes sense. 

I still feel a bit unsure about it. I've scaled the model up for a language task, 4000 output classes, and the loss is very small - although it is slowly learning.

**Comment by angusturner** [comment]
Yes I found this very confusing too, but I believe that it essentially reduces to the identity function.

e_hat = p_O

each element in the summation is a vector with all zeros except in the position k, where it takes the value p_O(k|…).

you can see that summing these just recreates p_O.


I believe that it is just written this way for generality - for example if the output distribution p_O was parameterised in some alternative way, then this function would mean “assemble the predicted probabilities back into a vector”

**Comment by thorinf** [comment]
Thanks. It's like an out product then, I was reading it like it was an inner product which made no sense.

Have you tried any large number of classes?
